version: '3.8'
services:
  arangodb:
    image: arangodb:latest
    environment:
      ARANGO_ROOT_PASSWORD: password  # Username: root
    ports:
      - 8529:8529
    volumes:
      - arangodb_data:/var/lib/arangodb3
      - arangodb_apps_data:/var/lib/arangodb3-apps

volumes:
  arangodb_data:
  arangodb_apps_data:
